[workspace]
members = [
    "common",
    "day01",
    "day02",
    "day03",
    "day04",
    "day05"
]
resolver = "3"

[workspace.package]
version = "0.1.0"
authors = ["John Bolton"]
description = "Advent of Code 2025 solutions"
