[package]
name = "day02"
edition = "2024"

[dependencies]
common = { path = "../common" }
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }

[features]
part2 = []
instrumented = ["part2", "serde", "serde_json"]
default = ["part2"]